- Cargo.toml
- README.md
- src/github/mod.rs
- src/main.rs
Basics of github interaction done.
> GitHub api interaction

- .travis.yml
- appveyor.yml
> Adds TravisCI build.

- README.md
> Adds details on release mode.

- rustfmt.toml
- src/github/mod.rs
- src/main.rs
Fixes https://github.com/matthewkmayer/release-party-BR/issues/16 .
> Adds rustfmt config, runs it on code.

- Cargo.toml
- src/github/mod.rs
- src/main.rs
Fixes https://github.com/matthewkmayer/release-party-BR/issues/17 .
> Apply clippy lints.

- src/github/mod.rs
Fixes https://github.com/matthewkmayer/release-party-BR/issues/14 .
> Less unwraps

- README.md
- src/github/mod.rs
- src/main.rs
Fixes https://github.com/matthewkmayer/release-party-BR/issues/28 .
> Adds dryrun behavior.

- src/github/mod.rs
- src/main.rs
Fixes https://github.com/matthewkmayer/release-party-BR/issues/32 .
> Rustfmt the code.

- src/github/mod.rs
- src/main.rs
Fixes https://github.com/matthewkmayer/release-party-BR/issues/10 .  Shaved ~10% off runtime but there's lots of network jitter.
> Reuse reqwest client

- README.md
- src/main.rs
Fixes https://github.com/matthewkmayer/release-party-BR/issues/40 .
> Spinal case only.

- README.md
- src/main.rs
Fixes https://github.com/matthewkmayer/release-party-BR/issues/42 .
> Handle URL generation for user.

- Cargo.toml
- src/github/mod.rs
- src/main.rs
Fixes worst case https://github.com/matthewkmayer/release-party-BR/issues/46 .  Still more to do though.
> Respect the ratelimit

- Cargo.toml
- src/github/mod.rs
- src/main.rs
- src/release-party.yml
Cleans up the `main` function nicely!  Prepping for making things more testable.
> Refactor of main

- src/main.rs
Gets the low hanging fruit of https://github.com/matthewkmayer/release-party-BR/issues/12 .
Should really figure out testing without talking to Github.  Mocktopus?
> Adds some tests

- Cargo.toml
- src/github/mod.rs
- src/main.rs
Probably the most we can do without more mocking.
> Add more tests

- .travis.yml
> Try publishing via TravisCI.

- TDD-notes.md
- src/main.rs
Fixes https://github.com/matthewkmayer/release-party-BR/issues/62 with fancy "did you mean" output to boot.
> Tdd org bits

- src/release-party.yml
Fixes https://github.com/matthewkmayer/release-party-BR/issues/69 . Depends on https://github.com/matthewkmayer/release-party-BR/pull/73 .
> Add docs on GitHub token

- src/github/mod.rs
Fixes https://github.com/matthewkmayer/release-party-BR/issues/70 .
> Better error on invalid github token.

- src/github/mod.rs
- src/main.rs
Fixes https://github.com/matthewkmayer/release-party-BR/issues/41 .
> Add pr links to release pr

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/release-party.yml
Fixes https://github.com/matthewkmayer/release-party-BR/issues/82 .
> Getting ready for 0.4.0 release.

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
Adds looking in ~/.ignoredrepos.toml for the list of repos to ignore.
> adding support for the ignored repos file in the home dir

- src/github/mod.rs
Print out more details if we got a weird response.
Kinda fixes https://github.com/matthewkmayer/release-party-BR/issues/91 .
> Add more details from github when something goes wrong.
